id: AC44AB3A8
title: Root Downfalls of the Vajra Vehicle
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:10:08.837353
  last_modified_at: 2022-03-01 02:10:08.837357
